# Generated by Django 5.0.4 on 2024-05-08 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buildings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Document_types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Document_users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_accepted', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('file', models.BinaryField()),
                ('date', models.DateField()),
                ('document_type_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.document_types')),
            ],
        ),
        migrations.CreateModel(
            name='Feed_to_document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.documents')),
            ],
        ),
        migrations.CreateModel(
            name='Feeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SmallIntegerField()),
                ('capacity', models.SmallIntegerField()),
                ('floor', models.SmallIntegerField()),
                ('section', models.SmallIntegerField()),
                ('building_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.buildings')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.BooleanField(null=True)),
                ('checked_room_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='rooms_checked', to='api.rooms')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='rooms_seeker', to='api.rooms')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule_types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User_types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('is_admin', models.BooleanField(default=False)),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.profiles')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.rooms')),
                ('user_type_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.user_types')),
            ],
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.AddField(
            model_name='document_users',
            name='document_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.documents'),
        ),
        migrations.AddField(
            model_name='feed_to_document',
            name='feed_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.feeds'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='schedule_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.schedule_types'),
        ),
        migrations.AddField(
            model_name='feeds',
            name='author_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.users'),
        ),
        migrations.AddField(
            model_name='documents',
            name='author_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.users'),
        ),
        migrations.AddField(
            model_name='document_users',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.users'),
        ),
    ]
